### ISSUE TITLE
Sonde data file inconsistent header

### ISSUE THREAD

**Issue by andybell** [ucd-cws/arcproject-wq-processing#37]
Fields inconsistent between different batches of sonde files. Not sure what would cause them to be altered. 

"DEP25" v "DepthX" - (see ARC_052715_CA1_WQ_10)

**Comment by nickrsan** [comment]
Oh right - I forgot about this - we can work around this by copying the field map and modifying it for those - I'll make sure that the data import has a field map option so that we use the correct one.

**Comment by andybell** [comment]
Another inconsistency issue - the units change. Some files have the depth field as meters while others are in feet.

**Comment by nickrsan** [comment]
Hmm - that's an interesting problem. Do you think this may be something worth bringing up with John to see if it's something we need to account for with future data inputs since we haven't dealt with it anywhere?

**Comment by andybell** [comment]
We might be able to account the different by parsing the units when loading the water quality file. Right now the row with the units gets tossed (https://github.com/ucd-cws/arcproject-wq-processing/blob/master/scripts/wqt_timestamp_match.py#L59) when parsing the raw water quality file.

The multiple units for the depth field is an issue for the transects as well as the vertical gain files (likely more important for the gain files since the water quality is limited to the top 1m of the water column). 

Besides the depth files, I've not noticed any other unit inconsistencies (but I haven't systematically checked).

**Comment by nickrsan** [comment]
OK, yeah, let's do that - we can build a nested dictionary (first key is the field, second key is the units) that has a multiplier value for the field. We may not need to do the first key on the field name, but I thought it would be safer in case we don't always want to transform the same unit to the same unit across all fields (ie, maybe sometimes we want feet in meters, but in another field we want it in km or something). Then it can throw a big loud warning if it encounters a unit it doesn't understand. 

In terms of where to do it, I'm thinking right when the file is read - we still toss the header then, but store it into another list that is then used for the lookup that transforms the numbers in the data frame.

That should be relatively simple to implement, I think. What do you think?

**Comment by nickrsan** [comment]
OK, I took a first crack at a bit of this in commit 203d0c5fedfabaae40481cf88debd6180f8bc5ed. There's a dict of dicts and a function to work with them (get_unit_conversion_scale). Passing the field and the current units into the function will return either a scaling factor or None. If it returns None, then no scaling should be applied, otherwise, we need to multiple the scaling factor by the whole field in the data frame. If it doesn't recognize the field or units, it raises an error saying that it can't reliably add the information because the units could be wrong.

**Comment by nickrsan** [comment]
Oh, and we could have it return 1 instead of None so that we can always just mutiply no matter what value is returned, but I thought it'd probably be more performant to return something that signals that no transformation should be applied and check for it before applying so that we only transform fields that need it.

**Comment by nickrsan** [comment]
OK, I think the inconsistent header issue is dealt with
