### ISSUE TITLE
Do we need to convert the linear referencing code to use wqt_timestamp_match.projection_spatial_reference for its SR code?

### ISSUE THREAD

**Issue by nickrsan** [ucd-cws/arcproject-wq-processing#55]
Working on fixing the segfault on the testing server when running the linear referencing tests and saw that 3310 is hardcoded in various places. Does it matter that it's using that if the rest of the code uses State Plane, or should is it fine since it's just used for the linear reference?

**Comment by andybell** [comment]
Yes. The linear referencing code should be updated. We'll need to check to see if it handles the reference line being in a different projection. 

One other issue with the linear reference code dealing with projections is that all the records in the XYevent table will need to be in a uniform projection. The could be dealt with by reprojecting the Lat/Long coords to match the projection of the reference line prior to the linear reference.

**Comment by andybell** [comment]
Updated linear_ref.py to use projection_spatial_reference that is set in wqt_timestamp_match.py. A better solution would be to use the spatial ref code that is in the water quality table since it is possible that there will be a mix of coordinate systems in the data base at some point. However, the XY event table requires that all records be the same spatial reference.
